[package]
name = "pong_6"
version = "0.1.0"
authors = ["Shub1427 <shub1493biswas@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5"
rand = "0.7"
nalgebra = "0.27.1"
alga       = "0.9"
ncollide2d = "0.20"
nphysics_testbed2d = "0.6.0"
nphysics2d = "0.12.3"
